image: gerardpslowey/emot:dependencies

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - cd src
    - pip install flake8
    - flake8 --version
    - flake8 --max-line-length=120 --ignore E401,E402 --exclude .env

pytest:
  stage: test
  script:
    - cd src
    - python --version
    - pytest -v
