image: python:latest

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - cd src
    - pip install flake8
    - flake8 --version
    - flake8 --max-line-length=120 --ignore E401,E402,W503,W504 --exclude env

pytest:
  stage: test
  script:
    - cd src
    - python -m venv env
    - source env/bin/activate
    - pip install -r ../res/requirements.txt
    - python --version
    - pytest -v
