urlsDict = {
    0: "www.google.com",
    1: "www.google.ie",
    2: "www.facebook.com",
    3: "docs.google.com",
    4: "mail.google.com",
    5: "accounts.google.com",
    6: "www.twitter.com",
    7: "discord.com",
    8: "www.reddit.com",
    9: "gitlab.computing.dcu.ie",
    10: "github.com",
    11: "www.messenger.com",
    12: "www.youtube.com",
    13: "stackoverflow.com",
    14: "dcu-ie.zoom.us",
    15: "www.bing.com",
}

tagsDict = {
    0: "[document]",
    1: "script",
    2: "noscript",
    3: "title",
    4: "style",
    5: "figure",
    6: "img",
    7: "iframe",
    8: "nav",
    9: "meta",
    10: "header",
    11: "head",
    12: "footer",
    13: "cookie",
}