# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(510, 460)
        Form.setMinimumSize(QtCore.QSize(510, 460))
        Form.setMaximumSize(QtCore.QSize(510, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emotHeader_2 = QtWidgets.QLabel(Form)
        self.emotHeader_2.setGeometry(QtCore.QRect(130, 20, 241, 100))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        self.emotHeader_2.setFont(font)
        self.emotHeader_2.setAlignment(QtCore.Qt.AlignCenter)
        self.emotHeader_2.setObjectName("emotHeader_2")
        self.emptyBox_3 = QtWidgets.QLabel(Form)
        self.emptyBox_3.setGeometry(QtCore.QRect(20, 80, 471, 341))
        self.emptyBox_3.setStyleSheet("border: 1px solid rgb(165, 165, 165);")
        self.emptyBox_3.setText("")
        self.emptyBox_3.setObjectName("emptyBox_3")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(50, 120, 411, 291))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.aboutText_2 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutText_2.sizePolicy().hasHeightForWidth())
        self.aboutText_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.aboutText_2.setFont(font)
        self.aboutText_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.aboutText_2.setWordWrap(True)
        self.aboutText_2.setOpenExternalLinks(False)
        self.aboutText_2.setObjectName("aboutText_2")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gitlabLink_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.gitlabLink_2.setFont(font)
        self.gitlabLink_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gitlabLink_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gitlabLink_2.setWordWrap(True)
        self.gitlabLink_2.setOpenExternalLinks(True)
        self.gitlabLink_2.setObjectName("gitlabLink_2")
        self.emptyBox_3.raise_()
        self.splitter.raise_()
        self.emotHeader_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "About"))
        self.emotHeader_2.setText(_translate("Form", "About"))
        self.aboutText_2.setText(_translate("Form", "eMot is a sentiment analysis application that takes your browsing history and extracts the emotions of the different sites you have visited.  "))
        self.label.setText(_translate("Form", "The text from these websites are scraped and processed to give you an indication of what sort of material you are reading. It is beneficial to know whether you are consuming media that has hateful emotions, sad emotions, or happy emotions. Your browsing history is never stored at any point.  "))
        self.label_2.setText(_translate("Form", "Find out more at:"))
        self.gitlabLink_2.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><a href=\"https://gitlab.computing.dcu.ie/sloweyg2/2021-ca400-gslowey-msavage\"><span style=\" text-decoration: underline; color:#0000ff;\">https://gitlab.computing.dcu.ie/sloweyg2/2021-ca400-gslowey-msavage</span></a></p></body></html>"))
import pyqt.resource_rc
# flake8: noqa


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
