# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metrics.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqt.resource_rc


class Ui_MetricsDashboard(object):
    def setupUi(self, MetricsDashboard):
        MetricsDashboard.setObjectName("MetricsDashboard")
        MetricsDashboard.resize(1458, 871)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MetricsDashboard.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MetricsDashboard)
        self.centralwidget.setObjectName("centralwidget")
        MetricsDashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MetricsDashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1458, 26))
        self.menubar.setObjectName("menubar")
        MetricsDashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MetricsDashboard)
        self.statusbar.setObjectName("statusbar")
        MetricsDashboard.setStatusBar(self.statusbar)

        self.retranslateUi(MetricsDashboard)
        QtCore.QMetaObject.connectSlotsByName(MetricsDashboard)

    def retranslateUi(self, MetricsDashboard):
        _translate = QtCore.QCoreApplication.translate
        MetricsDashboard.setWindowTitle(_translate("MetricsDashboard", "Metrics Dashboard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MetricsDashboard = QtWidgets.QMainWindow()
    ui = Ui_MetricsDashboard()
    ui.setupUi(MetricsDashboard)
    MetricsDashboard.show()
    sys.exit(app.exec_())
