# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emotQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Emot(object):
    def setupUi(self, Emot):
        Emot.setObjectName("Emot")
        Emot.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Emot)
        self.centralwidget.setObjectName("centralwidget")
        self.emotText = QtWidgets.QLabel(self.centralwidget)
        self.emotText.setGeometry(QtCore.QRect(270, 60, 251, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.emotText.setFont(font)
        self.emotText.setAlignment(QtCore.Qt.AlignCenter)
        self.emotText.setObjectName("emotText")
        self.browserChoice = QtWidgets.QComboBox(self.centralwidget)
        self.browserChoice.setGeometry(QtCore.QRect(190, 200, 141, 51))
        self.browserChoice.setObjectName("browserChoice")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.filterChoice = QtWidgets.QComboBox(self.centralwidget)
        self.filterChoice.setGeometry(QtCore.QRect(460, 200, 141, 51))
        self.filterChoice.setObjectName("filterChoice")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.browserLabel = QtWidgets.QLabel(self.centralwidget)
        self.browserLabel.setGeometry(QtCore.QRect(190, 170, 141, 31))
        self.browserLabel.setObjectName("browserLabel")
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(460, 170, 141, 31))
        self.dateLabel.setObjectName("dateLabel")
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(190, 280, 411, 71))
        self.goButton.setObjectName("goButton")
        Emot.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Emot)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Emot.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Emot)
        self.statusbar.setObjectName("statusbar")
        Emot.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(Emot)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout = QtWidgets.QAction(Emot)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPreferences = QtWidgets.QAction(Emot)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuNew.addAction(self.actionNew)
        self.menuNew.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Emot)
        QtCore.QMetaObject.connectSlotsByName(Emot)

    def retranslateUi(self, Emot):
        _translate = QtCore.QCoreApplication.translate
        Emot.setWindowTitle(_translate("Emot", "MainWindow"))
        self.emotText.setText(_translate("Emot", "eMot"))
        self.browserChoice.setStatusTip(_translate("Emot", "Choose the browser you use"))
        self.browserChoice.setItemText(0, _translate("Emot", "Chrome"))
        self.browserChoice.setItemText(1, _translate("Emot", "Edge"))
        self.browserChoice.setItemText(2, _translate("Emot", "Firefox"))
        self.browserChoice.setItemText(3, _translate("Emot", "Safari"))
        self.browserChoice.setItemText(4, _translate("Emot", "Brave"))
        self.browserChoice.setItemText(5, _translate("Emot", "Opera"))
        self.filterChoice.setStatusTip(_translate("Emot", "Choose the date filter"))
        self.filterChoice.setItemText(0, _translate("Emot", "All"))
        self.filterChoice.setItemText(1, _translate("Emot", "Hour"))
        self.filterChoice.setItemText(2, _translate("Emot", "Day"))
        self.filterChoice.setItemText(3, _translate("Emot", "Week"))
        self.filterChoice.setItemText(4, _translate("Emot", "Month"))
        self.filterChoice.setItemText(5, _translate("Emot", "Year"))
        self.browserLabel.setText(_translate("Emot", "Choose Your Browser "))
        self.dateLabel.setText(_translate("Emot", "Choose Date Filter"))
        self.goButton.setStatusTip(_translate("Emot", "Click to start the Sentiment Analysis"))
        self.goButton.setText(_translate("Emot", "Go!"))
        self.menuNew.setTitle(_translate("Emot", "File"))
        self.menuHelp.setTitle(_translate("Emot", "Help"))
        self.actionNew.setText(_translate("Emot", "New"))
        self.actionAbout.setText(_translate("Emot", "About"))
        self.actionPreferences.setText(_translate("Emot", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Emot = QtWidgets.QMainWindow()
    ui = Ui_Emot()
    ui.setupUi(Emot)
    Emot.show()
    sys.exit(app.exec_())
