# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'emotQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.emotText = QtWidgets.QLabel(self.centralwidget)
        self.emotText.setGeometry(QtCore.QRect(270, 30, 251, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.emotText.setFont(font)
        self.emotText.setAlignment(QtCore.Qt.AlignCenter)
        self.emotText.setObjectName("emotText")
        self.browserChoice = QtWidgets.QComboBox(self.centralwidget)
        self.browserChoice.setGeometry(QtCore.QRect(190, 200, 141, 51))
        self.browserChoice.setObjectName("browserChoice")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.browserChoice.addItem("")
        self.filterChoice = QtWidgets.QComboBox(self.centralwidget)
        self.filterChoice.setGeometry(QtCore.QRect(460, 200, 141, 51))
        self.filterChoice.setObjectName("filterChoice")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.filterChoice.addItem("")
        self.browserLabel = QtWidgets.QLabel(self.centralwidget)
        self.browserLabel.setGeometry(QtCore.QRect(190, 170, 141, 31))
        self.browserLabel.setObjectName("browserLabel")
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setGeometry(QtCore.QRect(460, 170, 141, 31))
        self.dateLabel.setObjectName("dateLabel")
        self.goButton = QtWidgets.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(190, 280, 411, 71))
        self.goButton.setObjectName("goButton")
        self.preferencesButton = QtWidgets.QPushButton(self.centralwidget)
        self.preferencesButton.setGeometry(QtCore.QRect(510, 457, 93, 41))
        self.preferencesButton.setObjectName("preferencesButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emotText.setText(_translate("MainWindow", "eMot"))
        self.browserChoice.setStatusTip(_translate("MainWindow", "Choose the browser you use"))
        self.browserChoice.setItemText(0, _translate("MainWindow", "Chrome"))
        self.browserChoice.setItemText(1, _translate("MainWindow", "Edge"))
        self.browserChoice.setItemText(2, _translate("MainWindow", "Firefox"))
        self.browserChoice.setItemText(3, _translate("MainWindow", "Safari"))
        self.browserChoice.setItemText(4, _translate("MainWindow", "Brave"))
        self.browserChoice.setItemText(5, _translate("MainWindow", "Opera"))
        self.filterChoice.setStatusTip(_translate("MainWindow", "Choose the date filter"))
        self.filterChoice.setItemText(0, _translate("MainWindow", "All"))
        self.filterChoice.setItemText(1, _translate("MainWindow", "Hour"))
        self.filterChoice.setItemText(2, _translate("MainWindow", "Day"))
        self.filterChoice.setItemText(3, _translate("MainWindow", "Week"))
        self.filterChoice.setItemText(4, _translate("MainWindow", "Month"))
        self.filterChoice.setItemText(5, _translate("MainWindow", "Year"))
        self.browserLabel.setText(_translate("MainWindow", "Choose Your Browser "))
        self.dateLabel.setText(_translate("MainWindow", "Choose Date Filter"))
        self.goButton.setStatusTip(_translate("MainWindow", "Click to start the Sentiment Analysis"))
        self.goButton.setText(_translate("MainWindow", "Go!"))
        self.preferencesButton.setText(_translate("MainWindow", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
